name: CI

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-cuda.tar.gz:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12

    - uses: cachix/cachix-action@v10
      with:
        name: futhark-mem-sc22
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Build cuda.tar.gz
      run: make cuda.tar.gz

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push docker image to DockerHub
      run: |
        docker load < cuda.tar.gz
        docker push munksgaard/futhark-mem-sc22:cuda

